name: island_cafe
description: "Start your day with a cup of coffee from Island Cafe"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icons & UI
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  shimmer_animation: ^2.2.2+1

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Networking (Standard http)
  http: ^1.6.0

  # Navigation
  go_router: ^17.0.0

  # Utils
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  image_picker: ^1.2.1

  # Data Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # Local Database (Using CE as requested)
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

  # Generators
  json_serializable: ^6.8.0
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  hive_ce_generator: 1.9.3

  # Lints
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
  - .env
