// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAJcqGgl0HFRH92dK74zGlBfk6MBfc5Q8',
    appId: '1:923919509100:android:bdebc8e01b68f22f681a49',
    messagingSenderId: '923919509100',
    projectId: 'islandcoffeeapp-62b47',
    storageBucket: 'islandcoffeeapp-62b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB29vZWUFF87Iu5n7dBr656VBtc_RLwoM',
    appId: '1:923919509100:ios:4e2cad3be7d1dc64681a49',
    messagingSenderId: '923919509100',
    projectId: 'islandcoffeeapp-62b47',
    storageBucket: 'islandcoffeeapp-62b47.firebasestorage.app',
    androidClientId:
        '923919509100-3i33hj5l3rlafi6jmohaq8c2bhn3ngt4.apps.googleusercontent.com',
    iosClientId:
        '923919509100-sm7uujmpfmlvajhbaru6ksc2okk3krrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.islandlinkFrontend',
  );
}
